language: node_js
node_js:
- '0.10'
before_install:
- npm install -g codeclimate-test-reporter
- npm install -g istanbul
- npm install -g bower
#script: npm run test-and-coverage
services:
- mongodb
env:
- NODE_ENV=test DEBUG="tea-party,tea-party:*"